apiVersion: v1
kind: Secret
metadata:
  name: backend-db-secret
type: Opaque
stringData:
  POSTGRES_DB: "users_db"
  POSTGRES_USER: "admin"
  POSTGRES_PASSWORD: "password123"
  DB_HOST: "database.c9a8v2kd3x4e.us-east-1.rds.amazonaws.com"
  DB_PORT: "5432"